import type { CatalogPagesContent } from "@/content/types";

const breadcrumbs = {
  parentBrand: "SAH Human",
  parentHref: "/sah-human",
} as const;

export const catalogPagesEn: CatalogPagesContent = {
  coaches: {
    eyebrow: "SAH Human",
    title: "1:1 Coaching with a Specialist",
    lead: "Find the right coach for your needs and book your first session directly.",
    breadcrumbCurrent: "1:1 Coaching",
    breadcrumbs,
    comingSoon: {
      title: "Coming Soon",
      body: "1:1 coaching is being prepared. Please check back soon — bookings and coach profiles will open here shortly.",
    },
    devNotice: {
      label: "Developer note",
      body: "Coach listings are powered by Sanity. Booking and payments integrate via Zoho Bookings once configured.",
    },
    list: {
      searchPlaceholder: "Search coaches…",
      searchAriaLabel: "Search coaches",
      clearSearchAriaLabel: "Clear search",
      filterAriaLabel: "Filter by specialty",
      countTemplate: "{count} coach(es) available",
      emptyTitle: "No coaches found",
      emptyBody: "Try adjusting your search or filter.",
      bookSession: "Book Session",
      sessionSuffix: "session",
      reviewsLabel: "reviews",
      specialties: [
        "All",
        "Leadership",
        "Career",
        "Business",
        "Wellbeing",
        "Communication",
        "Team",
      ],
    },
    groupCta: {
      title: "Looking for group coaching?",
      body: "Register your interest and our team will contact you with available group schedules.",
      button: "Register Interest",
    },
  },
  coachesGroup: {
    title: "Group Coaching",
    lead: "Register your interest and our team will contact you with available groups and schedules.",
    breadcrumbCurrent: "Group Coaching",
    breadcrumbs,
    formTitle: "Register Your Interest",
    formIntro:
      "Choose a programme and share your details. There is no financial commitment at this stage.",
    form: {
      programLegend: "Which programme interests you?",
      programRequired: "Please select a programme.",
      fullName: "Full Name *",
      fullNamePlaceholder: "Jane Smith",
      email: "Email Address *",
      phone: "Phone Number",
      organisation: "Organisation / Company",
      organisationPlaceholder: "Your employer (optional)",
      goals: "What do you hope to achieve?",
      goalsPlaceholder: "Share your goals briefly…",
      consent: "By submitting you agree to being contacted by the SAH team.",
      submit: "Submit Request",
      submitting: "Sending…",
      successTitle: "Thank you for your interest!",
      successBody:
        "We've received your request. Our team will contact you within 1-2 business days with available group schedules.",
      browseCoaches: "Browse Coaches",
    },
    programs: [
      {
        id: "leadership",
        title: "Leadership Accelerator",
        desc: "6-week group programme for mid-to-senior managers.",
      },
      {
        id: "founders",
        title: "Founders Circle",
        desc: "Peer coaching cohort for early-stage founders.",
      },
      {
        id: "women",
        title: "Women in Leadership",
        desc: "Empowering Saudi women to lead with confidence.",
      },
      {
        id: "wellbeing",
        title: "Team Wellbeing Series",
        desc: "Four sessions on resilience, energy, and belonging.",
      },
    ],
  },
  courses: {
    title: "Recorded Courses",
    lead: "Specialist course library — buy once, access forever from your dashboard.",
    breadcrumbCurrent: "Courses",
    breadcrumbs,
    comingSoon: {
      title: "Coming Soon",
      body: "Recorded courses are being prepared. Please check back soon — the course library and enrollment will open here shortly.",
    },
    devNotice: {
      label: "Note",
      body: "Courses are managed in Sanity. Enrollment, checkout, and video delivery integrate via Supabase, Moyasar/Tamara, and Mux once configured.",
    },
    getAccess: "Get Access",
    viewCourse: "View Course",
    lessonsLabel: "lessons",
    hoursLabel: "hrs",
  },
  courseProfile: {
    breadcrumbCourses: "Courses",
    levelLabel: "Level",
    durationLabel: "Duration",
    modulesLabel: "Modules",
    priceLabel: "Price",
    curriculumTitle: "Course Curriculum",
    curriculumLead: "Explore the modules included in this self-paced course.",
    previewLabel: "Free preview",
    emptyCurriculum: "The detailed curriculum will be published here soon.",
    comingSoon: "Coming Soon",
    purchaseNote:
      "Course access is not available yet. Checkout will open in a later release.",
  },
  coachProfile: {
    breadcrumbCoaches: "Coaches",
    reviewsLabel: "reviews",
    experienceLabel: "Experience:",
    languagesLabel: "Languages:",
    sessionLabel: "Session:",
    priceLabel: "Price:",
    sessionSuffix: "session",
    bookSession: "Book a Session",
    aboutTitle: "About the Coach",
    credentialsTitle: "Credentials & Certifications",
    bookSectionTitle: "Book a Session",
    bookSectionLead:
      "Select a slot that works for you. Live availability via Zoho Bookings once integrated.",
    authHint: "You need an account to confirm your booking and complete payment.",
    signIn: "Sign In",
    createAccount: "Create Account",
    authSub: "After signing in, choose a slot and complete payment.",
    reviewsTitle: "Client Reviews",
    reviewsFootnote:
      "* Reviews are placeholder data — will load from Supabase once configured.",
  },
};

export const catalogPagesAr: CatalogPagesContent = {
  coaches: {
    eyebrow: "سعة هيومن",
    title: "تدريب فردي مع مدرب متخصص",
    lead: "اختر المدرب الأنسب لاحتياجاتك واحجز جلستك الأولى مباشرة.",
    breadcrumbCurrent: "تدريب فردي",
    breadcrumbs,
    comingSoon: {
      title: "قريباً",
      body: "التدريب الفردي قيد الإعداد. يُرجى العودة قريباً — ستتوفر هنا الملفات الشخصية وحجز الجلسات قريباً.",
    },
    devNotice: {
      label: "ملاحظة للمطورين",
      body: "قوائم المدربين مُدارة عبر سانِتي. الحجز والدفع يتكاملان مع Zoho Bookings عند الإعداد.",
    },
    list: {
      searchPlaceholder: "ابحث عن مدرب...",
      searchAriaLabel: "البحث عن مدرب",
      clearSearchAriaLabel: "مسح البحث",
      filterAriaLabel: "تصفية حسب التخصص",
      countTemplate: "{count} مدرب متاح",
      emptyTitle: "لا توجد نتائج",
      emptyBody: "جرّب البحث بكلمات أخرى أو تغيير الفلتر.",
      bookSession: "احجز جلسة",
      sessionSuffix: "جلسة",
      reviewsLabel: "تقييم",
      specialties: [
        "الكل",
        "القيادة",
        "المهني",
        "الأعمال",
        "الرفاه",
        "التواصل",
        "الفريق",
      ],
    },
    groupCta: {
      title: "هل تبحث عن تدريب جماعي؟",
      body: "سجّل اهتمامك وسيتواصل معك فريقنا لمشاركتك جدول الجلسات المتاحة.",
      button: "سجّل اهتمامك",
    },
  },
  coachesGroup: {
    title: "التدريب الجماعي",
    lead: "سجّل اهتمامك وسيتواصل معك فريقنا لمشاركتك المجموعات والجداول المتاحة.",
    breadcrumbCurrent: "التدريب الجماعي",
    breadcrumbs,
    formTitle: "سجّل اهتمامك",
    formIntro:
      "اختر البرنامج الذي يناسبك وأكمل بياناتك. لا يوجد التزام مالي في هذه المرحلة.",
    form: {
      programLegend: "اختر البرنامج الذي يناسبك:",
      programRequired: "يرجى اختيار برنامج.",
      fullName: "الاسم الكامل *",
      fullNamePlaceholder: "محمد الأحمد",
      email: "البريد الإلكتروني *",
      phone: "رقم الجوال",
      organisation: "الجهة / الشركة",
      organisationPlaceholder: "اسم جهتك (اختياري)",
      goals: "ما الذي تأمل في تحقيقه؟",
      goalsPlaceholder: "شاركنا أهدافك بشكل مختصر...",
      consent: "بإرسال هذا النموذج توافق على التواصل معك من قبل فريق سعة.",
      submit: "أرسل طلبي",
      submitting: "جارٍ الإرسال...",
      successTitle: "شكراً لاهتمامك!",
      successBody:
        "استلمنا طلبك وسيتواصل معك فريقنا خلال 1-2 يوم عمل لمشاركتك الجداول المتاحة.",
      browseCoaches: "استعرض المدربين",
    },
    programs: [
      {
        id: "leadership",
        title: "مسرّع القيادة",
        desc: "برنامج جماعي لمدة 6 أسابيع للمدراء.",
      },
      {
        id: "founders",
        title: "دائرة المؤسسين",
        desc: "مجموعة تدريب أقران للمؤسسين في المراحل المبكرة.",
      },
      {
        id: "women",
        title: "المرأة في القيادة",
        desc: "تمكين المرأة السعودية من القيادة بثقة.",
      },
      {
        id: "wellbeing",
        title: "سلسلة رفاه الفريق",
        desc: "أربع جلسات حول المرونة والطاقة والانتماء.",
      },
    ],
  },
  courses: {
    title: "الدورات المسجلة",
    lead: "مكتبة دورات متخصصة — اشترِ مرة واحدة، وصول دائم من لوحة تحكمك.",
    breadcrumbCurrent: "الدورات",
    breadcrumbs,
    comingSoon: {
      title: "قريباً",
      body: "الدورات المسجلة قيد الإعداد. يُرجى العودة قريباً — ستتوفر هنا مكتبة الدورات والتسجيل قريباً.",
    },
    devNotice: {
      label: "ملاحظة",
      body: "الدورات مُدارة في سانِتي. التسجيل والدفع والفيديو يتكاملون مع Supabase وMoyasar/Tamara وMux عند الإعداد.",
    },
    getAccess: "ابدأ الآن",
    viewCourse: "عرض الدورة",
    lessonsLabel: "درس",
    hoursLabel: "ساعات",
  },
  courseProfile: {
    breadcrumbCourses: "الدورات",
    levelLabel: "المستوى",
    durationLabel: "المدة",
    modulesLabel: "الوحدات",
    priceLabel: "السعر",
    curriculumTitle: "محتوى الدورة",
    curriculumLead: "استعرض الوحدات المشمولة في هذه الدورة الذاتية.",
    previewLabel: "معاينة مجانية",
    emptyCurriculum: "سيُنشر المحتوى التفصيلي للدورة هنا قريباً.",
    comingSoon: "قريباً",
    purchaseNote: "الوصول إلى الدورة غير متاح حالياً. سيُفتح الدفع في إصدار لاحق.",
  },
  coachProfile: {
    breadcrumbCoaches: "المدربون",
    reviewsLabel: "تقييم",
    experienceLabel: "الخبرة:",
    languagesLabel: "اللغات:",
    sessionLabel: "مدة الجلسة:",
    priceLabel: "السعر:",
    sessionSuffix: "جلسة",
    bookSession: "احجز جلسة",
    aboutTitle: "نبذة عن المدرب",
    credentialsTitle: "المؤهلات والشهادات",
    bookSectionTitle: "احجز جلستك",
    bookSectionLead:
      "اختر موعداً مناسباً. سيظهر هنا جدول متاح من Zoho Bookings بعد الإعداد.",
    authHint: "تحتاج إلى حساب لإتمام الحجز ومعالجة الدفع.",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    authSub: "بعد تسجيل الدخول، اختر الموعد وأتمّ الدفع.",
    reviewsTitle: "آراء العملاء",
    reviewsFootnote: "* التقييمات مؤقتة. ستُحمَّل من Supabase عند الإعداد.",
  },
};
